<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" />
      <PackageReference Include="Newtonsoft.Json.Interface" Version="8.0.1" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
      <PackageReference Include="Umbraco.Cms.Core" Version="15.4.3" />
    </ItemGroup>

  <ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Umbraco.Translations.Api.Tests</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbraco.Translations.Cache\Umbraco.Translations.Cache.csproj" />
    <ProjectReference Include="..\Umbraco.Translations.Services\Umbraco.Translations.Services.csproj" />
  </ItemGroup>

</Project>
